### PR TITLE
[CHANGE] fix(AnnotationContentOverlay): do not show the component when a modal is open

### LINKED ISSUE #570: Highlight hover effect exists while creating Signature
If you highlight text and then attempt to create a signature then the hover effect still fires.  Users have pointed out that it's distracting.

Note, may exist in other modal/popup situations.

image

### PR DESCRIPTION
**Pull request by ZhijieZhang**
Checks if the mouse in moving on a modal component to decide if we are hovering on an annotation. Fixes #570.

### CODE REVIEW

**Comment by ZhijieZhang** [comment]
Close for a while as I noticed there're more components we need to take into account. Will reopen once it's fixed.

**Comment by ZhijieZhang** [comment]
@achenPDFTron Can you review this when you have time? Thanks.

**Comment by achenPDFTron** [comment]
Note to self, able to replicate the bug on https://www.pdftron.com/samples/web/samples/viewing/viewing/

**Comment by achenPDFTron** [comment]
@ZhijieZhang 
When I have the redaction modal opened, I can still hover over the redaction annot I have created. Is that intentional?

**Comment by ZhijieZhang** [comment]
I can reproduce the issue where the redaction annotation can still be hovered when the modal is open, but the comment text won't show up anymore.

I guess if we want to fix the redaction hovering issue we'd want it in another PR.

**Pull request merged**
