### PR TITLE
[CHANGE] Fixed regresstion where switching between the thumbnail panel and another panel will result in warnings in the console.

### PR DESCRIPTION
**Pull request by ZhijieZhang**

### CODE REVIEW

**Comment by awy3** [comment]
The changes seem good. However when I was testing this, I still see some warnings

ThumbnailWarning

It's not as bad as before but still show up when moving between pages really fast

**Comment by ZhijieZhang** [comment]
Hi Andrew, thanks for the feedback. I will take a look at the remaining issue when I have time.

**Comment by awy3** [comment]
You can merge it if you want, it improve the current problem.

**Comment by ZhijieZhang** [comment]
@awy3 I looked into this a bit and it seems that the error is coming from WebViewer rendering pages, not thumbnails, since just scrolling the thumbnail panels won't output this warning message.

I will merge the changes in. Thanks for reviewing it.

**Pull request merged**
