### PR TITLE
Fix Japanese translations

### PR DESCRIPTION
**Pull request by Ryosuke-ob**
#949

### CODE REVIEW

**Review by bollain — APPROVED** [review]
Thanks for this PR @Ryosuke-ob! We have reviewed them internally and are approved. I will merge this PR, and you should be able to get the updated translations from our nightly stable build of 8.2 in the next 24 hours.

**Comment by Ryosuke-ob** [comment]
Thank you very much!

**Comment by ashashish** [comment]
@bollain Can you confirm which Server build and/or UI version we need to update our PDFTron server to for getting this?

**Comment by bollain** [comment]
@ashashish you will be able to get the updated translations in the stable nightly builds for WebViewer client 8.2:
https://www.pdftron.com/nightly/#stable/

If they are not updated as of today, they will tomorrow. The nightly build takes about 24 hours to update.

**Pull request merged**
