### PR TITLE
Fix/toolbar count measurement tool

### PR DESCRIPTION
**Pull request by JimmyLin39**
Fix the count measurement tool is not displayed on the new toolbar UI.
image

### CODE REVIEW

**Comment by khein-pdftron** [comment]
This still have the issue that you can't style them right? @JimmyLin39 
Did you find a fix for it?

**Comment by JimmyLin39** [comment]
Yeah, I found a quick fix is that if I change the [Icon] to `Check`, it got all the styles. https://github.com/XodoDocs/webviewer/pull/1392 @khein-pdftron

**Comment by khein-pdftron** [comment]
@JimmyLin39 Sounds good. Let me know when core is up to date so I can try this.

**Comment by JimmyLin39** [comment]
@khein-pdftron Core is up to date, thanks.

**Comment by khein-pdftron** [comment]
Screen Shot 2020-07-11 at 11 42 28 PM

I used latest master. Still doesn't seem to be working.

**Pull request merged**
