### PR TITLE
Bug fix/tooltip text overflow

### PR DESCRIPTION
**Pull request by achenPDFTron**

### CODE REVIEW

**Comment by achenPDFTron** [comment]
Solution came from https://css-tricks.com/snippets/css/prevent-long-urls-from-breaking-out-of-container.

It looked like we were missing one line:
word-break: break-all;
word-break: break-word; // not supported in Edge

**Comment by achenPDFTron** [comment]
Picture of what the fix looks like (working on IE11, FF, Edge, Chrome).

Original problem:
https://trello.com/c/iP1tEZ6v/532-tooltip-text-overflows-improperly-for-wrong-text

Using only the letter "a"
image


Using 10 paragraphs of lorem ipsum:
image

**Comment by ZhijieZhang** [comment]
@achenPDFTron  There's one lint error. Could you please fix it? I don't think you introduced it though...

**Comment by achenPDFTron** [comment]
@ZhijieZhang addressed linter problem

**Pull request merged**
